version: "2.4"
services: 
  nocodb: 
    depends_on: 
      root_db: 
        condition: service_healthy
    environment: 
      NC_DB: "mssql://root_db:1433?u=sa&p=Password123.&d=root_db"
    image: "nocodb/nocodb:latest"
    ports: 
      - "8080:8080"
    restart: always
    volumes: 
      - "nc_data:/usr/app/data"
  root_db: 
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Password123.
    healthcheck: 
      interval: 10s
      retries: 10
      start_period: 10s
      test: "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"$$SA_PASSWORD\" -Q \"SELECT 1\" || exit 1"
      timeout: 3s
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    restart: always
    volumes: 
      - "db_data:/var/opt/mssql"
volumes: 
  db_data: {}
  nc_data: {}
